// <auto-generated />
using Cinema.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Cinema.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.1");

            modelBuilder.Entity("Cinema.Models.Movies", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Content_admin_id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Length")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content_admin_id = 101,
                            Director = "Christopher Nolan",
                            ImageUrl = "https://m.media-amazon.com/images/M/MV5BMjAxMzY3NjcxNF5BMl5BanBnXkFtZTcwNTI5OTM0Mw@@._V1_.jpg   ",
                            Length = 148,
                            Name = "Inception",
                            Summary = "Inception is a 2010 science fiction action film...",
                            Type = "Sci-Fi"
                        },
                        new
                        {
                            Id = 2,
                            Content_admin_id = 102,
                            Director = "Frank Darabont",
                            ImageUrl = "https://m.media-amazon.com/images/M/MV5BNDE3ODcxYzMtY2YzZC00NmNlLWJiNDMtZDViZWM2MzIxZDYwXkEyXkFqcGdeQXVyNjAwNDUxODI@._V1_.jpg",
                            Length = 142,
                            Name = "The Shawshank Redemption",
                            Summary = "The Shawshank Redemption is a 1994 American drama film...",
                            Type = "Drama"
                        },
                        new
                        {
                            Id = 3,
                            Content_admin_id = 103,
                            Director = "Francis Ford Coppola",
                            ImageUrl = "https://m.media-amazon.com/images/M/MV5BM2MyNjYxNmUtYTAwNi00MTYxLWJmNWYtYzZlODY3ZTk3OTFlXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_.jpg",
                            Length = 175,
                            Name = "The Godfather",
                            Summary = "The Godfather is a 1972 American crime film directed by...",
                            Type = "Crime"
                        },
                        new
                        {
                            Id = 4,
                            Content_admin_id = 104,
                            Director = "Christopher Nolan",
                            ImageUrl = "https://m.media-amazon.com/images/M/MV5BMTMxNTMwODM0NF5BMl5BanBnXkFtZTcwODAyMTk2Mw@@._V1_.jpg",
                            Length = 152,
                            Name = "The Dark Knight",
                            Summary = "The Dark Knight is a 2008 superhero film directed by...",
                            Type = "Action"
                        },
                        new
                        {
                            Id = 5,
                            Content_admin_id = 105,
                            Director = "Quentin Tarantino",
                            ImageUrl = "https://m.media-amazon.com/images/M/MV5BNGNhMDIzZTUtNTBlZi00MTRlLWFjM2ItYzViMjE3YzI5MjljXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_.jpg",
                            Length = 154,
                            Name = "Pulp Fiction",
                            Summary = "Pulp Fiction is a 1994 American crime film written and directed by...",
                            Type = "Crime"
                        },
                        new
                        {
                            Id = 6,
                            Content_admin_id = 106,
                            Director = "Robert Zemeckis",
                            ImageUrl = "https://m.media-amazon.com/images/M/MV5BNWIwODRlZTUtY2U3ZS00Yzg1LWJhNzYtMmZiYmEyNmU1NjMzXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_FMjpg_UX1000_.jpg",
                            Length = 142,
                            Name = "Forrest Gump",
                            Summary = "Forrest Gump is a 1994 American drama film directed by...",
                            Type = "Drama"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
